spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/no_code_platform
    username: root
    password: 123456
  session:
    store-type: redis
    # session 30 天过期
    timeout: 2592000
  data:
    redis:
      host: localhost
      ttl: 3600
      port: 6379
      password:
langchain4j:
  community:
    dashscope:
      chat-model:
        api-key: sk-355fdaeddf5743078b7d4c9efde61980
        model-name: qwen-max
        parameters:
          response-format: json
          format-on: true
        is-multimodal-model: false
      embedding-model:
        api-key: sk-355fdaeddf5743078b7d4c9efde61980
        model-name: text-embedding-v4
      streaming-chat-model:
        api-key: sk-355fdaeddf5743078b7d4c9efde61980
        model-name: qwen3-max-2025-09-23
        parameters:
          response-format: json
          format-on: false
        is-multimodal-model: false
      image-model:
        api-key: sk-355fdaeddf5743078b7d4c9efde61980
        model-name: wanx2.1-t2i-turbo
    redis:
      host: localhost
      ttl: 3600
      port: 6379
      password:
pexels:
  api-key: vz44hcIuOnoHxX8JJyUoVW9a7HHHsv5EICXudH2UMZKvrl7RbDox28M5
minio:
  endpoint: http://localhost:9000
  access-key: admin
  secret-key: password123
  bucket: nocodeplatform
  public-endpoint: http://localhost:9000
