spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/no_code_platform
    username: root
    password: 123456

langchain4j:
  community:
    dashscope:
      chat-model:
        api-key: sk-355fdaeddf5743078b7d4c9efde61980
        model-name: qwen-max
        parameters:
          response-format: json
      embedding-model:
        api-key: sk-355fdaeddf5743078b7d4c9efde61980
        model-name: text-embedding-v4
      streaming-chat-model:
        api-key: sk-355fdaeddf5743078b7d4c9efde61980
        model-name: qwen-max
    redis:
      host: localhost
      ttl: 3600
      port: 6379
      password: